-- 回滚 0001_init 迁移
DROP TABLE IF EXISTS storages;
DROP TABLE IF EXISTS personal_access_tokens;
DROP TABLE IF EXISTS oauth_accounts;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS shares;
DROP TABLE IF EXISTS photo_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS album_photos;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS verify_codes;
DROP TABLE IF EXISTS users;
